"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var clients_controllers_1 = require("../controllers/clients.controllers");
var router = (0, express_1.Router)();
router.get('/', clients_controllers_1.index);
router.get('/login', clients_controllers_1.loginClient);
router.get('/quick', clients_controllers_1.indexClient);
router.get('/client/categorias', clients_controllers_1.tagsClient);
router.get('/client/farmacias', clients_controllers_1.farmClient);
router.get('/client/restaurantes', clients_controllers_1.restClient);
router.get('/client/Abarrotes', clients_controllers_1.bisClient);
router.get('/farmacias/productos', clients_controllers_1.getRestProductos);
router.get('/client/productos', clients_controllers_1.getProductos);
router.get('/abarrotes/productos', clients_controllers_1.getAbaProductos);
router.get('/farmacias/productos', clients_controllers_1.getFarmProductos);
router.get('/client/order', clients_controllers_1.orderProduct);
router.get('/client/orderlist', clients_controllers_1.orderList);
router.get('/client/user', clients_controllers_1.userClient);
exports.default = router;
